version: "3"

services:
    qr_faas_management:
        build:
            context: .

        ports:
            - "8000:8000"

        volumes:
            - ./qr_faas_management:/qr_faas_management

        command: python manage.py runserver 0.0.0.0:8000
        restart: always

volumes:
    pgdata:




